from django.db import models
from django.utils import translation

_ = translation.gettext_lazy


class NumeratorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

    def get_by_natural_key(self, ctype, date_start, date_end):
        return self.get(
            ctype=ctype, date_start=date_start, date_end=date_end)


class Numerator(models.Model):
    """ ContentTypeCounter is used as autogenerated number register
        like autonumber for uuid based Model """

    class Meta:
        verbose_name = _('Numerator')
        verbose_name_plural = _('Numerators')
        unique_together = ('app_label', 'model', 'prefix', 'reset_mode', 'year', 'month')

    YEARLY = 'YEAR'
    MONTHLY = 'MONTH'
    FIXED = 'NEVER'
    RESET_MODE = (
        (YEARLY, _('Yearly Reset')),
        (MONTHLY, _('Montly Reset')),
        (FIXED, _('NEVER')),
    )

    objects = NumeratorManager()

    app_label = models.CharField(
        max_length=50,
        verbose_name=_('application'))
    model = models.CharField(
        max_length=50,
        verbose_name=_('model'))
    prefix = models.CharField(
        max_length=50,
        null=True, blank=True,
        verbose_name=_('prefix'))
    reset_mode = models.CharField(
        max_length=50,
        choices=RESET_MODE,
        default=YEARLY,
        verbose_name=_('reset mode'))
    year = models.IntegerField()
    month = models.IntegerField(default=0)
    counter = models.PositiveIntegerField(
        default=0, verbose_name=_('Counter'))

    def __str__(self):
        return str(self.model)

    def natural_key(self):
        natural_key = (self.app_label, self.model, self.year, self.month)
        return natural_key

    def increase_counter(self):
        self.counter += 1
        return self.counter

    def decrease_counter(self):
        i = 1 if self.counter > 0 else 0
        self.counter -= i
        return self.counter

    def reset_counter(self):
        self.counter = 0
        return self.counter

    def get_mode(self):
        return Numerator.YEARLY

    @staticmethod
    def get_for_instance(instance):
        opts = instance._meta
        defaults = {
            'app_label': opts.app_label,
            'model': opts.model_name,
            'prefix': instance.get_doc_prefix(),
            'year': instance.get_date_field().year,
            'month': instance.get_date_field().month if instance.reset_mode == Numerator.MONTHLY else 0
        }
        get_or_create = Numerator.objects.get_or_create
        ct_counter, created = get_or_create(**defaults, defaults=defaults)
        return ct_counter


class NumeratorMixin(models.Model):
    """ Mixin for Numerator Model """

    class Meta:
        abstract = True

    numerator = None
    reset_mode = Numerator.YEARLY
    zero_fill = 4
    doc_prefix = ''

    reg_number = models.PositiveIntegerField(
        null=True,
        blank=True,
        editable=False,
        verbose_name=_('Reg number'))
    inner_id = models.CharField(
        null=True,
        blank=True,
        unique=True,
        editable=False,
        max_length=50,
        verbose_name=_('Inner ID'))

    def get_doc_prefix(self):
        doc_prefix = getattr(self, 'doc_prefix', '')
        return doc_prefix

    def get_date_field(self):
        return getattr(self, 'created_at')

    def format_date(self, form="%y%m"):
        return self.get_date_field().strftime(form)

    def format_number(self):
        return str(self.reg_number).zfill(self.zero_fill)

    def format_inner_id(self):
        form = [
            self.get_doc_prefix(),
            self.format_date(),
            self.format_number()
        ]
        self.inner_id = '{}{}{}'.format(*form)
        return self.inner_id

    def get_numerator(self):
        """ Get or create numerator """
        numerator = Numerator.get_for_instance(self)
        return numerator

    def update_inner_id(self):
        """
        Register and get Numerator instance for
        this model, Get latest counter value and then
        generate and set inner_id
        """
        # Get Numerator instance for this model
        if self.numerator is None:
            self.numerator = self.get_numerator()

        # If reg_number is None get new one
        if self.reg_number is None:
            self.reg_number = self.numerator.increase_counter()

        # If reg number > counter set new counter value
        if self.reg_number > self.numerator.counter:
            self.numerator.counter = self.reg_number

        return self.format_inner_id()

    def save(self, *args, **kwargs):
        if self.numerator is None:
            self.update_inner_id()
        self.numerator.save()
        super().save(*args, **kwargs)